export const SET_INSTALL_DETAILS = "SET_INSTALL_DETAILS";
export const SET_ADMIN_COMPONENT = "SET_ADMIN_COMPONENT";
export const SET_SETTINGS = "SET_SITE_SETTINGS";
export const ADD_PRODUCT_DETAILS = "ADD_PRODUCT_DETAILS";