export enum Types {
    SET_INSTALL_DETAILS = "SET_INSTALL_DETAILS",
    SET_ADMIN_COMPONENT = "SET_ADMIN_COMPONENT",
    SET_SETTINGS = "SET_SITE_SETTINGS",
    ADD_PRODUCT_DETAILS = "ADD_PRODUCT_DETAILS",
    ADD_PRODUCT = "ADD_PRODUCT",
    SET_STATUS = "SET_STATUS",
    LOAD_PRODUCTS = "LOAD_PRODUCTS",
    APPEND_PRODUCTS = "APPEND_PRODUCTS"
}